#install.packages("igraph")
library(igraph)


actorsMapTotal <- graph(c("FEWSNET","MAGA",
                          "FEWSNET","FAO",
                          "FEWSNET","WFP",
                          "FEWSNET","USDA",
                          "FEWSNET","USGS",
                          "FEWSNET","USAID",
                          "URL","WFP",
                          "URL","WWF",
                          "URL","CATIE",
                          "URL","INSIVUMEH",
                          "ANACAFE","MAGA",
                          "ANACAFE","INSIVUMEH",
                          "ANACAFE","INAB",
                          "ANACAFE","USDA",
                          "ANACAFE","PROMOCAFE",
                          "ANACAFE","CCAFS",
                          "ANACAFE","CAMARGO",
                          "ANACAFE","OIRSA",
                          "ANACAFE","F.Neumann",
                          "ANACAFE","UTZ",
                          "ANACAFE","ESRI",
                          "ANACAFE","IICA",
                          "ANACAFE","PROCAGICA",
                          "ANACAFE","BID Fomin",
                          "ANACAFE","CRS",
                          "ARNPG","ANACAFE",
                          "ARNPG","CONAP",
                          "ARNPG","INAB",
                          "ARNPG","MAGA",
                          "ARNPG","MARN",
                          "ARNPG","INSIVUMEH",
                          "ARNPG","CONRED",
                          "ARNPG","ENCA",
                          "ARNPG","AMSA",
                          "MAGA","MARN",
                          "MAGA","ICTA",
                          "MAGA","FAO",
                          "MAGA","UE",
                          "MAGA","IICA",
                          "MAGA","CONAP",
                          "MAGA","INSIVUMEH",
                          "MAGA","FEWSNET",
                          "MAGA","USAC",
                          "MAGA","IARNA",
                          "MAGA","INAB",
                          "MAGA","ACH",
                          "MAGA","PMA",
                          "MAGA","SICA",
                          "MAGA","Plan Trifinio",
                          "MAGA","CATIE",
                          "INSIVUMEH","MAGA",
                          "INSIVUMEH","FEWSNET",
                          "INSIVUMEH","MARN",
                          "INSIVUMEH","SESAN",
                          "INSIVUMEH","ANACAFE",
                          "INSIVUMEH","IPCC",
                          "INSIVUMEH","ICC",
                          "INSIVUMEH","USAID",
                          "INSIVUMEH","FAO",
                          "CDRO","MAGA",
                          "CDRO","MARN",
                          "CDRO","INAB",
                          "CDRO","USAC",
                          "CDRO","RESCA",
                          "MARN","MAGA",
                          "MARN","FAUSAC",
                          "MARN","INAB",
                          "MARN","CONAP",
                          "MARN","ICC",
                          "MARN","ANACAFE",
                          "MARN","CDRO",
                          "Mision de Taiwan","ANACAFE",
                          "Mision de Taiwan","MAGA",
                          "Mision de Taiwan","ICTA",
                          "Mision de Taiwan","OIRSA",
                          "Mision de Taiwan","IICA",
                          "Mision de Taiwan","AGROCLIMA",
                          "Mision de Taiwan","USAC",
                          "Mision de Taiwan","DIPLAN",
                          "Mision de Taiwan","INSIVUMEH",
                          "ICC","MARN",
                          "ICC","APIB",
                          "ICC","ASAZGUA",
                          "ICC","INSIVUMEH",
                          "ICC","MAGA",
                          "ICC","FAO",
                          "ICC","NOAA",
                          "ICC","FEWSNET",
                          "FAO","MAGA",
                          "FAO","FENURGUA",
                          "FAO","MARN",
                          "FAO","SEGEPLAN",
                          "FAO","MINFIN",
                          "FAO","INSIVUMEH",
                          "FAO","SGCCC",
                          "ACH","MAGA",
                          "ACH","MARN",
                          "ACH","SESAN",
                          "ATRIDEST Guatemala","MAGA",
                          "ATRIDEST Guatemala","ANACAFE",
                          "ATRIDEST Guatemala","Plan Trifinio",
                          "Agropecuaria","MAGA",
                          "Agropecuaria","INAB",
                          "Agropecuaria","PROSA",
                          "Agmomia","MAGA",
                          "Agmomia","MARN",
                          "Municipo Olopa","MAGA",
                          "Municipo Olopa","MARN",
                          "Municipo Olopa","ANACAFE",
                          "Municipo Olopa","AGENXPRONT",
                          "Micracuenca Rio Shu Sho","MAGA",
                          "Plan Trifinio","MAGA",
                          "Plan Trifinio","MARN",
                          "PMA","MAGA",
                          "PMA","MIDES",
                          "PMA","OMM",
                          "PMA","SESAN",
                          "Maya Ajchak","CDRO",
                          "Maya Ajchak","MARN",
                          "Parcialidad Tax","Juab",
                          "Parcialidad Tax","CDRO",
                          "Juab","CDRO",
                          "ADIC","MAGA",
                          "Aspsiacion Durazno","MAGA",
                          "Aspsiacion Durazno","ANACAFE",
                          "Aspsiacion Durazno","PROCAGICA",
                          "Aspsiacion Durazno","Confinio Shtal",
                          "Sumam Hi'kel", "MAGA",
                          "Sumam Hi'kel", "MARN",
                          "USAC","MAGA",
                          "USAC","MARN",
                          "USAC","INSIVUMEH",
                          "USAC","ASORECH",
                          "USAC","ASEDECHI",
                          "USAC","PMA",
                          "USAC","ICTA",
                          "USAC","Mancom. Copanchorti"))
plot(actorsMapTotal,
     vertex.color = "light green",
     vertex.size = 12.5,
     edge.color = "orange",
     vertex.frame.color = "light green",
     vertex.label.color = "black",
     edge.arrow.size = .075,
     vertex.label.cex = .65,
     frame = TRUE,
     main = "Actors Map of Guatemala",
     margin = 0)
actorsMapTotal
