

#Mesa connections


#Centro-Sur Connections
CSConnections <- graph(c("MAGA","ITCA",
                      "MAGA","FAO",
                      "MAGA","UE",
                      "MAGA","MARN",
                      "MAGA","IICA",
                      "MAGA","CONAP",
                      "MAGA","INSIVUMEH",
                      "MAGA","FEWSNET",
                      "MAGA","USAC",
                      "MAGA","IARNA",
                      "ICC","MARN",
                      "ICC","APIB",
                      "ICC","ASAZGUA",
                      "ICC","INSIVUMEH",
                      "ICC","CIAT",
                      "ICC","MAGA",
                      "ICC","FAO",
                      "ICC","IRI",
                      "ICC","NOAA",
                      "ICC","FEWSNET",
                      "ANACAFE","MAGA",
                      "ANACAFE","INSIVUMEH",
                      "ANACAFE","INAB",
                      "ANACAFE","USDA",
                      "ANACAFE","CIAT",
                      "ANACAFE","PROMOCAFE",
                      "ANACAFE","CCAFS",
                      "ANACAFE","CAMARGO",
                      "ANACAFE","OIRSA",
                      "ANACAFE","F.Neumann",
                      "ANACAFE","UTZ",
                      "ANACAFE","ESRI",
                      "ANACAFE","IICA",
                      "URL","WFP",
                      "URL","WWF",
                      "URL","INSIVUMEH",
                      "URL","CATIE",
                      "ARNPG","ANACAFE",
                      "ARNPG","CONAP",
                      "ARNPG","INAB",
                      "ARNPG","MAGA",
                      "ARNPG","MARN",
                      "ARNPG","INSIVUMEH",
                      "ARNPG","CONRED",
                      "ARNPG","ENCA",
                      "ARNPG","AMSA",
                      "INSIVUMEH","MAGA",
                      "INSIVUMEH","FEWSNET",
                      "INSIVUMEH","MARN",
                      "INSIVUMEH","SESAN",
                      "INSIVUMEH","ANACAFE",
                      "INSIVUMEH","IPCC",
                      "INSIVUMEH","ICC",
                      "INSIVUMEH","USAID",
                      "INSIVUMEH","FAO",
                      "CDRO","MAGA",
                      "CDRO","MARN",
                      "CDRO","USAC",
                      "CDRO","INAB",
                      "CDRO","RESCA",
                      "MARN","MAGA",
                      "MARN","USAC",
                      "MARN","INAB",
                      "MARN","CONAP",
                      "MARN","ICC",
                      "USAC","MAGA",
                      "USAC","MARN",
                      "USAC","INSIVUMEH",
                      "USAC","ASORECH",
                      "USAC","ASEDECHI",
                      "USAC","PMA",
                      "USAC","ICTA",
                      "USAC","Mancomunidad Copan Chorti",
                      "FEWSNET","MAGA",
                      "FEWSNET","FAO",
                      "FEWSNET","WFP",
                      "FEWSNET","USDA",
                      "FEWSNET","USGS",
                      "FEWSNET","USAID",
                      "Mision de Taiwan","MAGA",
                      "Mision de Taiwan","ICTA",
                      "Mision de Taiwan","OIRSA",
                      "Mision de Taiwan","IICA",
                      "Mision de Taiwan","ANACAFE",
                      "Mision de Taiwan","AGROCLIMA",
                      "Mision de Taiwan","USAC",
                      "Mision de Taiwan","INSIVUMEH",
                      "FAO","MAGA",
                      "FAO","FENURGUA",
                      "FAO","MARN",
                      "FAO","SEGEPLAN",
                      "FAO","MINFIN",
                      "FAO","INSIVUMEH",
                      "FAO","USAC"))
plot(CSConnections,
     vertex.color = "gray",
     vertex.size = 12.5,
     edge.color = 'black',
     edge.arrow.size = .075,
     vertex.label.cex = .65,
     main = "Centro-Sur Connections")
CSConnections


#Totonicapan Connections
TotoConnections <- graph(c("Parcialidad Tax","Juab",
                     "MARN","CDRO",
                     "Maya Ajchak","CDRO",
                     "Maya Ajchak","MARN",
                     "CDRO","Parcialidad Tax",
                     "CDRO","Juab",
                     "MAGA","MARN",
                     "ADIC","MAGA"))
plot(TotoConnections,
     vertex.color = "yellow",
     vertex.size = 12.5,
     edge.arrow.size = .075,
     vertex.label.cex = .65,
     edge.color = 'black',
     main = "Totonicapán Connections")
TotoConnections


#Xela Connections
XelaConnections <- graph(c("Sumam Hi'kel","MAGA",
                     "Sumam Hi'kel","MARN"))
plot(XelaConnections,
     vertex.color = "orange",
     vertex.size = 12.5,
     edge.arrow.size = .075,
     vertex.label.cex = .65,
     edge.color = 'black',
     main = "Xela Connections")
XelaConnections


#Chiquimula Connections
ChiquiConnections <- graph(c("MAGA","ICTA",
                  "MAGA","MARN",
                  "MAGA","INAB",
                  "MAGA","ACH",
                  "MAGA","PMA",
                  "MAGA","FAO",
                  "MAGA","SICA",
                  "MAGA","Plan Trifinio",
                  "MAGA","CATIE",
                  "MARN","ANACAFE",
                  "MARN","MAGA",
                  "ANACAFE","BID Formin",
                  "ANACAFE","CRS",
                  "ANACAFE","PROCAGICA",
                  "Municipio Olopa","ANACAFE",
                  "Municipio Olopa","MAGA",
                  "Municipio Olopa","MARN",
                  "Municipio Olopa","MAGENXPRONT",
                  "ACH","MAGA",
                  "ACH","MARN",
                  "ACH","SESAN",
                  "ATRIDEST Guatemala","MAGA",
                  "ATRIDEST Guatemala","ANACAFE",
                  "ATRIDEST Guatemala","Plan Trifinio",
                  "Agropecuaria","MAGA",
                  "Agropecuaria","INAB",
                  "Agropecuaria","PROSA",
                  "Agmomia","MAGA",
                  "Agmomia","MARN",
                  "Micracuenca Rio Shu Sho","MAGA",
                  "Plan Trifinio","MAGA",
                  "Plan Trifinio","MARN",
                  "Asociacion Durazno","MAGA",
                  "Asociacion Durazno","ANACAFE",
                  "Asociacion Durazno","PROCAFICA",
                  "Asociacion Durazno","Confinio Shtal",
                  "PMA","MAGA",
                  "PMA","MIDES",
                  "PMA","OMM",
                  "PMA","SESAN"))
plot(ChiquiConnections,
     vertex.color = "tan",
     vertex.size = 12.5,
     edge.arrow.size = .075,
     vertex.label.cex = .65,
     edge.color = 'black',
     main = "Chiquimula Connections")
ChiquiConnections


#El Progreso Connections
